// <auto-generated />
using System;
using DemoAppQLTH.Infrastructure.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace QuanLyTruongHocV1.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    partial class SchoolDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DemoAppQLTH.Domain.Diem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("GiaTri")
                        .HasColumnType("float");

                    b.Property<Guid>("HocKyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HocSinhId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MonHocId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HocKyId");

                    b.HasIndex("MonHocId");

                    b.HasIndex("HocSinhId", "MonHocId", "HocKyId")
                        .IsUnique();

                    b.ToTable("Diems");
                });

            modelBuilder.Entity("DemoAppQLTH.Domain.DiemThanhPhan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("GiaTri")
                        .HasColumnType("float");

                    b.Property<Guid?>("GiaoVienId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HocKyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HocSinhId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Loai")
                        .HasColumnType("int");

                    b.Property<Guid>("MonHocId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GiaoVienId");

                    b.HasIndex("HocKyId");

                    b.HasIndex("MonHocId");

                    b.HasIndex("HocSinhId", "MonHocId", "HocKyId");

                    b.HasIndex("HocSinhId", "MonHocId", "HocKyId", "Loai", "NgayNhap");

                    b.ToTable("DiemThanhPhans");
                });

            modelBuilder.Entity("DemoAppQLTH.Domain.GhiDanh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HocKyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HocSinhId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LopHocId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HocKyId");

                    b.HasIndex("LopHocId");

                    b.HasIndex("HocSinhId", "HocKyId")
                        .IsUnique();

                    b.ToTable("GhiDanhs");
                });

            modelBuilder.Entity("DemoAppQLTH.Domain.HocKy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DaKhoa")
                        .HasColumnType("bit");

                    b.Property<int>("KyThu")
                        .HasColumnType("int");

                    b.Property<string>("NamHoc")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NamHoc", "KyThu")
                        .IsUnique();

                    b.ToTable("HocKys");
                });

            modelBuilder.Entity("DemoAppQLTH.Domain.KhoiMon", b =>
                {
                    b.Property<int>("Khoi")
                        .HasColumnType("int");

                    b.Property<Guid>("MonHocId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Khoi", "MonHocId");

                    b.HasIndex("MonHocId");

                    b.ToTable("KhoiMons");
                });

            modelBuilder.Entity("DemoAppQLTH.Domain.LopHoc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GVCNId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Khoi")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("GVCNId");

                    b.HasIndex("Ten")
                        .IsUnique();

                    b.ToTable("LopHocs");
                });

            modelBuilder.Entity("DemoAppQLTH.Domain.MonHoc", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HeSo")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Ten")
                        .IsUnique();

                    b.ToTable("MonHocs");
                });

            modelBuilder.Entity("DemoAppQLTH.Domain.Nguoi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Email")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Loai")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Ma")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Ma")
                        .IsUnique();

                    b.ToTable("Nguoi");

                    b.HasDiscriminator<string>("Loai").HasValue("Nguoi");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DemoAppQLTH.Domain.PhanCong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GiaoVienId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HocKyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LopHocId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MonHocId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HocKyId");

                    b.HasIndex("LopHocId");

                    b.HasIndex("MonHocId");

                    b.HasIndex("GiaoVienId", "MonHocId", "LopHocId", "HocKyId")
                        .IsUnique();

                    b.ToTable("PhanCongs");
                });

            modelBuilder.Entity("DemoAppQLTH.Domain.Admin", b =>
                {
                    b.HasBaseType("DemoAppQLTH.Domain.Nguoi");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("DemoAppQLTH.Domain.GiaoVien", b =>
                {
                    b.HasBaseType("DemoAppQLTH.Domain.Nguoi");

                    b.HasDiscriminator().HasValue("GiaoVien");
                });

            modelBuilder.Entity("DemoAppQLTH.Domain.HocSinh", b =>
                {
                    b.HasBaseType("DemoAppQLTH.Domain.Nguoi");

                    b.HasDiscriminator().HasValue("HocSinh");
                });

            modelBuilder.Entity("DemoAppQLTH.Domain.Diem", b =>
                {
                    b.HasOne("DemoAppQLTH.Domain.HocKy", "HocKy")
                        .WithMany("Diems")
                        .HasForeignKey("HocKyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DemoAppQLTH.Domain.HocSinh", "HocSinh")
                        .WithMany("Diems")
                        .HasForeignKey("HocSinhId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DemoAppQLTH.Domain.MonHoc", "MonHoc")
                        .WithMany("Diems")
                        .HasForeignKey("MonHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HocKy");

                    b.Navigation("HocSinh");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("DemoAppQLTH.Domain.DiemThanhPhan", b =>
                {
                    b.HasOne("DemoAppQLTH.Domain.GiaoVien", "GiaoVien")
                        .WithMany()
                        .HasForeignKey("GiaoVienId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DemoAppQLTH.Domain.HocKy", "HocKy")
                        .WithMany("DiemThanhPhans")
                        .HasForeignKey("HocKyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DemoAppQLTH.Domain.HocSinh", "HocSinh")
                        .WithMany("DiemThanhPhans")
                        .HasForeignKey("HocSinhId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DemoAppQLTH.Domain.MonHoc", "MonHoc")
                        .WithMany("DiemThanhPhans")
                        .HasForeignKey("MonHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GiaoVien");

                    b.Navigation("HocKy");

                    b.Navigation("HocSinh");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("DemoAppQLTH.Domain.GhiDanh", b =>
                {
                    b.HasOne("DemoAppQLTH.Domain.HocKy", "HocKy")
                        .WithMany("GhiDanhs")
                        .HasForeignKey("HocKyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DemoAppQLTH.Domain.HocSinh", "HocSinh")
                        .WithMany("GhiDanhs")
                        .HasForeignKey("HocSinhId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DemoAppQLTH.Domain.LopHoc", "LopHoc")
                        .WithMany("GhiDanhs")
                        .HasForeignKey("LopHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HocKy");

                    b.Navigation("HocSinh");

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("DemoAppQLTH.Domain.KhoiMon", b =>
                {
                    b.HasOne("DemoAppQLTH.Domain.MonHoc", "MonHoc")
                        .WithMany()
                        .HasForeignKey("MonHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("DemoAppQLTH.Domain.LopHoc", b =>
                {
                    b.HasOne("DemoAppQLTH.Domain.GiaoVien", "GVCN")
                        .WithMany("LopChuNhiems")
                        .HasForeignKey("GVCNId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("GVCN");
                });

            modelBuilder.Entity("DemoAppQLTH.Domain.PhanCong", b =>
                {
                    b.HasOne("DemoAppQLTH.Domain.GiaoVien", "GiaoVien")
                        .WithMany("PhanCongs")
                        .HasForeignKey("GiaoVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DemoAppQLTH.Domain.HocKy", "HocKy")
                        .WithMany("PhanCongs")
                        .HasForeignKey("HocKyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DemoAppQLTH.Domain.LopHoc", "LopHoc")
                        .WithMany("PhanCongs")
                        .HasForeignKey("LopHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DemoAppQLTH.Domain.MonHoc", "MonHoc")
                        .WithMany("PhanCongs")
                        .HasForeignKey("MonHocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GiaoVien");

                    b.Navigation("HocKy");

                    b.Navigation("LopHoc");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("DemoAppQLTH.Domain.HocKy", b =>
                {
                    b.Navigation("DiemThanhPhans");

                    b.Navigation("Diems");

                    b.Navigation("GhiDanhs");

                    b.Navigation("PhanCongs");
                });

            modelBuilder.Entity("DemoAppQLTH.Domain.LopHoc", b =>
                {
                    b.Navigation("GhiDanhs");

                    b.Navigation("PhanCongs");
                });

            modelBuilder.Entity("DemoAppQLTH.Domain.MonHoc", b =>
                {
                    b.Navigation("DiemThanhPhans");

                    b.Navigation("Diems");

                    b.Navigation("PhanCongs");
                });

            modelBuilder.Entity("DemoAppQLTH.Domain.GiaoVien", b =>
                {
                    b.Navigation("LopChuNhiems");

                    b.Navigation("PhanCongs");
                });

            modelBuilder.Entity("DemoAppQLTH.Domain.HocSinh", b =>
                {
                    b.Navigation("DiemThanhPhans");

                    b.Navigation("Diems");

                    b.Navigation("GhiDanhs");
                });
#pragma warning restore 612, 618
        }
    }
}
